secrets:
  # Note: Github personal access token
  #       Not the token for registering self-hosted runner
  github_access-token:
    file: ./access-token

services:
  socket:
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      AUTH: 1
      BUILD: 1
      CONTAINERS: 1
      EXEC: 1
      IMAGES: 1
      INFO: 1
      SESSION: 1
      CONFIGS: 1
    healthcheck:
      # Test on docker healthcheck endpoint
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:2375/v1.35/_ping" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 2s

  runner:
    build:
      context: .
    secrets:
      - github_access-token
    env_file: .env
    environment:
      DOCKER_HOST: socket:2375
      ACCESS_TOKEN_FILE: /run/secrets/github_access-token
